# Generated by Django 4.0.3 on 2022-04-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movietable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.AddField(
            model_name='movietable',
            name='isPublished',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='movietable',
            name='description',
            field=models.TextField(verbose_name='Movie Description'),
        ),
        migrations.AlterField(
            model_name='movietable',
            name='image',
            field=models.CharField(max_length=50, verbose_name='Movie Image'),
        ),
        migrations.AlterField(
            model_name='movietable',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Movie Name'),
        ),
    ]
