# Generated by Django 4.0.3 on 2022-04-06 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_delete_movie_movietable_ispublished_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieTable',
            new_name='Movie',
        ),
    ]
